    scalar JSONObject
    scalar JSON

    type Query {
        getPosts : [Post]
        getPostById : Post
        getUsers : [User]
        getUserById (id: String!): User
        getOptions : [Option]
        getOptionById (id: String!) : Option
        getCategories: [Category]
        getCategoryById (id: String!): Category
    }